plugin_spec_version: v2
extension: plugin
product: ["insightconnect"]
name: carbon_black_response
title: Cb Response
vendor: rapid7
support: rapid7
status: []
description: Cb Response is the most complete endpoint detection and response solution
  available to security teams
version: 3.1.7
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/carbon_black_response
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
tags:
      type: string
      required: false
      title: Total Tags
    last_hit:
      type: date
      required: false
      title: Last Hit
    from_alliance:
      type: boolean
      required: false
      title: From Alliance
  feed:
    provider_url:
      type: string
      required: false
      title: Provider URL
    ssl_client_crt:
      type: string
      required: false
      title: SSL Client Certificate
    local_rating:
      type: integer
      required: false
      title: Local Rating
    requires_who:
      type: string
      required: false
      title: Requires Who
    icon_small:
      type: bytes
      required: false
      title: Icon Small
    id:
      type: integer
      required: false
      title: ID
    category:
      type: string
      required: false
      title: Category
    display_name:
      type: string
      required: false
      title: Display Name
    use_proxy:
      type: boolean
      required: false
      title: Use Proxy
    feed_url:
      type: string
      required: false
      title: Feed URL
    username:
      type: string
      required: false
      title: Username
    validate_server_cert:
      type: boolean
      required: false
      title: Validate Server Cert
    ssl_client_key:
      type: string
      required: false
      title: SSL Client Key
    manually_added:
      type: boolean
      required: false
      title: Manually Added
    password:
      type: string
      required: false
      title: Password
    icon:
      type: bytes
      required: false
      title: Icon
    provider_rating:
      type: number
      required: false
      title: Provider Rating
    name:
      type: string
      required: false
      title: Name
    tech_data:
      type: string
      required: false
      title: Tech Data
    requires:
      type: string
      required: false
      title: Requires
    enabled:
      type: boolean
      required: false
      title: Enabled
    summary:
      type: string
      required: false
      title: Summary
    requires_what:
      type: string
      required: false
      title: Requires What
    order:
      type: integer
      required: false
      title: Order
  sensor:
    systemvolume_total_size:
      description: Total size of system volume
      title: Systemvolume Total Size
      type: string
    os_environment_display_string:
      description: OS environment display string
      title: OS Environment Display String
      type: string
    sensor_uptime:
      description: How long the sensor has been up
      title: Sensor Uptime
      type: string
    is_isolating:
      description: Is sensor isolated
      title: Is Isolating
      type: boolean
    id:
      description: Sensor ID
      title: ID
      type: integer
    build_id:
      description: Sensor build ID
      title: Build ID
      type: integer
    uptime:
      description: Uptime
      title: Uptime
      type: string
    computer_dns_name:
      description: DNS name of the computer
      title: Computer DNS Name
      type: string
    physical_memory_size:
      description: Physical memory size
      title: Physical Memory Size
      type: string
    next_checkin_time:
      description: Next check-in time
      title: Next Check-In Time
      type: string
    sensor_health_message:
      description: Sensor health message
      title: Sensor Health Message
      type: string
    boot_id:
      description: Boot ID
      title: Boot ID
      type: string
    computer_sid:
      description: Computer SID
      title: Computer SID
      type: string
    event_log_flush_time:
      description: Event log flush time
      title: Event Log Flush Time
      type: string
    computer_name:
      description: Computer name
      title: Computer Name
      type: string
    license_expiration:
      description: License expiration
      title: License Expiration
      type: string
    network_adapters:
      description: Network adapters
      title: Network Adapters
      type: string
    sensor_health_status:
      description: Sensor health status
      title: Sensor Health Status
      type: integer
    registration_time:
      description: Registration time
      title: Registration Time
      type: string
    systemvolume_free_size:
      description: Systemvolume free size
      title: Systemvolume Free Size
      type: string
    notes:
      description: Notes
      title: Notes
      type: string
    network_isolation_enabled:
      description: Network isolation enabled
      title: Network Isolation Enabled
      type: boolean
    os_environment_id:
      description: OS environment ID
      title: OS Environment ID
      type: integer
    cookie:
      description: Cookie
      title: Cookie
      type: integer
    build_version_string:
      description: Build version string
      title: Build Version String
      type: string
    last_checkin_time:
      description: Last checkin time
      title: Last Checkin Time
      type: string
    group_id:
      description: Group ID
      title: Group ID
      type: integer
    display:
      description: Display
      title: Display
      type: boolean
    uninstall:
      description: Uninstall
      title: Uninstall
      type: boolean
    found:
      description: If sensor was found
      title: Found
      type: boolean
connection:
  api_key:
    title: API Key
    type: credential_secret_key
    description: API token found in your Carbon Black profile
    required: true
  url:
    title: URL
    type: string
    description: Carbon Black Server API URL
    default: https://127.0.0.1/api/bit9platform/v1
    required: true
  ssl_verify:
    title: SSL Verify
    type: boolean
    description: SSL certificate verification
    default: true
    required: true
actions:
  list_alerts:
    title: List Alerts
    description: List Carbon Black alerts with given parameters
    input:
      query:
        type: string
        description: Accepts the same data as the search box on the Process Search
          page
        required: false
        title: Query String
      rows:
        type: integer
        description: How many rows of data to return. Default is 10
        default: 10
        required: false
        title: Rows
      start:
        type: integer
        description: What row of data to start at. Default is 0
        default: 0
        required: false
    output:
      alerts:
        description: The lists of alerts
        type: '[]alert'
        required: false
  list_processes:
    title: List Processes
    description: List Carbon Black processes with given parameters
    input:
      query:
        type: string
        description: Accepts the same data as the search box on the Process Search
          page
        required: false
        title: Query String
      rows:
        type: integer
        description: How many rows of data to return. Default is 10
        default: 10
        required: false
        title: Rows
      start:
        type: integer
        description: What row of data to start at. Default is 0
        default: 0
        required: false
    output:
      processes:
        description: The list of processes
        type: '[]process'
        required: false
  list_binaries:
    title: List Binaries
    description: List Carbon Black binaries with given parameters
    input:
      query:
        type: string
        description: Accepts the same data as the search box on the Process Search
          page
        required: false
        title: Query String
      rows:
        type: integer
        description: How many rows of data to return. Default is 10
        default: 10
        required: false
        title: Rows
      start:
        type: integer
        description: What row of data to start at. Default is 0
        default: 0
        required: false
    output:
      binaries:
        description: The list of binaries
        type: '[]binary'
        required: false
  list_watchlists:
    title: List Watchlists
    description: List all watchlists
    output:
      watchlists:
        description: The list of watchlists
        type: '[]watchlist'
        required: false
  list_feeds:
    title: List Feeds
    description: List all feeds
    output:
      feeds:
        description: The list of feeds
        type: '[]feed'
        required: false
  list_sensors:
    title: List Sensors
    description: List all sensors
    input:
      id:
        type: string
        description: The sensor ID
        required: false
        title: ID
      hostname:
        type: string
        description: The sensor hostname
        required: false
        title: Hostname
      ip:
        type: string
        description: The sensor IP address
        required: false
        title: IP Address
      groupid:
        type: string
        description: The sensor group ID
        required: false
        title: Group ID
    output:
      sensors:
        description: The list of sensors
        type: '[]sensor'
        required: false
  get_binary:
    title: Get Binary
    description: Retrieve a binary by its MD5 Hash
    input:
      hash:
        description: An MD5 hash
        type: string
        required: true
        title: Hash
    output:
      binary:
        description: A resulting binary, Base64-encoded
        type: bytes
        required: false
  blacklist_hash:
    title: Blacklist Hash
    description: Ban a hash given its MD5
    input:
      md5_hash:
        description: An MD5 hash
        type: string
        required: true
        title: MD5 Hash
    output:
      success:
        type: boolean
        description: Status of request - true if successful, false otherwise
        required: false
  add_watchlist:
    title: Add Watchlist
    description: Adds a watchlist
    input:
      name:
        type: string
        description: Watchlist name
        required: true
      index_type:
        type: string
        description: Either modules or events for binary and process watchlists, respectively
        required: true
        default: modules
        enum:
        - modules
        - events
      query:
        type: string
        description: Raw Carbon Black query that this watchlist matches
        required: true
    output:
      id:
        description: The ID of the created watchlist
        type: string
        required: false
        title: ID
  add_feed:
    title: Add Feed
    description: Adds a feed
    input:
      feed_url:
        description: The URL of the feed to add
        type: string
        required: false
      force:
        type: boolean
        default: false
        description: Add feed even if the feed URL is already in use
        required: false
      enabled:
        type: boolean
        description: Enable feed
        required: false
      username:
        description: Username
        type: string
        required: false
      password:
        description: Password
        type: password
        required: false
      cert:
        description: Certificate file
        type: file
        required: false
      key:
        description: Key
        type: file
        required: false
      use_proxy:
        description: Whether or not to use proxy
        type: boolean
        required: false
      validate_server_cert:
        description: Whether or not to validate server certificate
        type: boolean
        required: false
    output:
      id:
        description: The ID of the added feed
        type: integer
        required: false
        title: ID
  delete_feed:
    title: Delete Feed
    description: Deletes a feed
    input:
      id:
        description: The ID of the feed
        type: string
        required: true
        title: ID
      force:
        type: boolean
        description: Force deletion of all matches if multiple matches found
        required: true
        title: Force
    output:
      success:
        type: boolean
        description: Whether or not the deletion was successful
        required: false
  delete_watchlist:
    title: Delete Watchlist
    description: Deletes a watchlist
    input:
      id:
        description: The ID of the watchlist
        type: string
        required: true
        title: ID
      force:
        type: boolean
        description: Force deletion of all matches if multiple matches found
        required: true
        title: Force
    output:
      success:
        type: boolean
        description: Whether or not the deletion was successful
        required: false
  update_alert:
    title: Update Alert
    description: Updates or Resolves an Alert in Carbon Black
    input:
      id:
        description: 'Unique ID of the alert. Example: 1cb11d0d-f86b-415d-aeb3-05f085973fbb'
        type: string
        required: true
        title: Unique ID
      status:
        description: The status to update
        type: string
        enum:
        - Resolved
        - Unresolved
        - In Progress
        - False Positive
        required: true
        default: Resolved
        title: Status
    output:
      success:
        type: boolean
        description: Whether or not the update was successful
        required: false
  isolate_sensor:
    title: Isolate Sensor
    description: Isolates a sensor from the network
    input:
      hostname:
        description: Hostname of the sensor to isolate
        type: string
        required: false
        title: Hostname
    output:
      success:
        type: boolean
        description: Whether or not the isolation was successful
        required: false
  unisolate_sensor:
    title: Unisolate Sensor
    description: Brings a sensor back into the network
    input:
      hostname:
        description: Hostname of the sensor to unisolate
        type: string
        required: false
        title: Hostname
    output:
      success:
        type: boolean
        description: Whether or not the unisolation was successful
        required: false
triggers:
  new_alert:
    title: New Alert
    description: Fires when a new alert is found
    output:
      alert:
        type: alert
        description: Carbon Black alert
        required: false
        title: Alert
